name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # add more python versions here, as needed
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
