name: Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME_PREFIX: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME_PREFIX }}-appname

      - name: Build and push go app
        uses: docker/build-push-action@v6
        with:
          context: sample-go-app
          file: sample-go-app/Dockerfile
          push: true
          build-args: |
            VERSION=${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
